### ISSUE TITLE
[Feature] Specify both city and country

### ISSUE THREAD

**Issue by szimmer** [koenderks/rcityviews#10]
**Is your feature request related to a problem? Please describe.**
I was trying to make a map of Durham, NC. There are 3 Durhams in the database and interactively, you get prompted asking which one but I'd love this to be an input to the function.

**Describe the solution you'd like**
Update `list_cities` function to return a data.frame with both name and country. Output would look something like this:

```
    name                  country   lat   long population
1 Durham                   Canada 44.18 -80.82       2898
2 Durham           United Kingdom 54.78  -1.60      46406
3 Durham United States of America 35.98 -78.91     208426
```

Update cityview to allow country as an optional input.

**Describe alternatives you've considered**
None

**Additional context**
This would be useful for people using R markdown or something without interactivity.

**Comment by koenderks** [comment]
Thanks! In the latest development version I have implemented several ways to do this. First, `list_cities()` now behaves as requested, with:

```
rcityviews::list_cities(match = "Durham")
        name                  country   lat   long
10010 Durham                   Canada 44.18 -80.82
10011 Durham           United Kingdom 54.78  -1.60
10012 Durham United States of America 35.98 -78.91
```

When calling `cityview()` you can now provide it with a row of the output of `list_cities()`, e.g.,

```
city <-rcityviews::list_cities(match = "Durham")[3, ]
cityview(city)
```

or you can provide it with an entirely new city made using `new_city()`, e.g.,

```
city <- new_city(name = "Durham", country = "US", lat = 35.98, long = -78.91)
cityview(city)
```

Let me know if it works for you!
