### ISSUE TITLE
Control Over Text Size

### ISSUE THREAD

**Issue by aschmidt-amplify** [koenderks/rcityviews#12]
**Is your feature request related to a problem? Please describe.**
In making the following map, I noticed the names seem inappropriately large, causing overlap and distraction from the map itself.
```
myTheme <- list(
  colors = list(
    background = "#232323",
    water = NA,
    landuse = NA,
    contours = NA,
    streets = "#FF8200",
    rails = c("#FF8200", "#232323"),
    buildings = NA,
    text = "#ffffff",
    waterlines = NA
  ),
  font = list(
    family = "serif",
    face = "bold",
    append = "\u2014"
  ),
  size = list(
    borders = list(
      contours = 0.3,
      water = 0.4,
      canal = 0.5,
      river = 0.6
    ),
    streets = list(
      path = 0.2,
      residential = 0.4,
      structure = 0.5,
      tertiary = 0.7,
      secondary = 0.8,
      primary = 0.9,
      motorway = 1,
      rails = 0.75,
      runway = 3
    )
  )
)
cityview(name = "Knoxville", zoom = 0.5, theme = myTheme)
```
![image](https://user-images.githubusercontent.com/95245211/235378987-2f674032-4b02-423c-a889-5d7bd0a06a6f.png)

**Describe the solution you'd like**
Do we have control over the country, city, long/lat, and attribution size and font?

**Comment by koenderks** [comment]
Thanks, I will look into this! As a quick temporary fix: The size of the text that you see depends on the dimensions of the exported figure and the quality (dpi). The map can be saved/exported in the recommended size and quality by calling:

ggplot2::ggsave(filename = "plot.png", plot = p, height = 500, width = 500, units = "mm", dpi = 100)

Or by providing cityview() with a filename directly, as is shown in the readme.

**Comment by koenderks** [comment]
You can now use `myTheme[["font"]][["scale"]]` to set the scaling factor for the font. Below is an example with `scale = 0.5`.

```
myTheme <- list(
  colors = list(
    background = "#232323",
    water = NA,
    landuse = NA,
    contours = NA,
    streets = "#FF8200",
    rails = c("#FF8200", "#232323"),
    buildings = NA,
    text = "#ffffff",
    waterlines = NA
  ),
  font = list(
    family = "serif",
    face = "bold",
    scale = 0.5,
    append = "\u2014"
  ),
  size = list(
    borders = list(
      contours = 0.3,
      water = 0.4,
      canal = 0.5,
      river = 0.6
    ),
    streets = list(
      path = 0.2,
      residential = 0.4,
      structure = 0.5,
      tertiary = 0.7,
      secondary = 0.8,
      primary = 0.9,
      motorway = 1,
      rails = 0.75,
      runway = 3
    )
  )
)
cityview(name = "Knoxville", zoom = 0.5, theme = myTheme, filename = "plot.png")
```

![plot](https://user-images.githubusercontent.com/25059399/235413912-67601fe4-af8e-4e64-b60b-592f153c4356.png)

Hope that helps!
