### ISSUE TITLE
[Feature] Way to obtain/save data only so it's quicker and more effective to try out different plot styles afterward

### ISSUE THREAD

**Issue by rafabelokurows** [koenderks/rcityviews#13]
First of all, thanks for the amazing package, it produces some great maps right out of the box! 🤘🏻

I was wondering if there is a way of obtaining the OSM attributes for a particular city first and saving them as an intermediate R object so I could test out different styles and plot parameters afterward.

If I'm not missing anything here, as of now, every time you run the function "citiyview", it retrieves data from that city all over again. It would be awesome if you could load data from the city first and then only call the "styling function" or however you wanna call it.

Thank you in advance! Keep up the good work!

**Comment by koenderks** [comment]
Hi! Thanks for making this issue. You are right, the way this is currently done is quite inefficient. The cityview function has to query all the data for a city every time you want to apply a different theme. It would indeed be nice if you could apply some sort of change_style function. 

I'll try if I can find some way to do this!
