### ISSUE TITLE
Disable certain type of buildings (or other OSM features)

### ISSUE THREAD

**Issue by stalkerGH** [koenderks/rcityviews#19]
I'd like to disable (not hide but avoid downloading and processing) of certain types of buildings from Overpass API server. In _osmdata_'s documentation for `add_osm_feature` function (https://docs.ropensci.org/osmdata/reference/add_osm_feature.html) I found how to do that in "pure" _osmdata_ package:

> value
> value for feature key; can be negated with an initial exclamation mark, value = "!this", and can also be a vector, value = c ("this", "that").

But I don't know the valid syntax for calling this in _rcityviews_. Piece of code in `builders.R` say: 

`obj <- .getOsmFeatures(bbox, cropped, border, features = "\"building\"")`

But how to add features I don't want?

**Comment by koenderks** [comment]
I'm afraid that is not possible. The idea of the package was always to make it very easy to make these types of images but by doing so it also takes away some of the freedom that you would have if you would code this completely from scratch.

If you want to have full control over the images, it's probably best to work in a local clone of the repository and change the internal code yourself to give the desired result. I believe you can add a `key` argument to `getOsmFeatures()` to specify different types of buildings. But that would then require you to give all the types of buildings that you want, which may be a lot.

**Comment by stalkerGH** [comment]
Thanks for feedback. I do not propose global code change :) I'd like to change it "local only". Do you suggest that I should explicitly use something similar to `waterway = river`, `waterway = canal` and so on but for different types of buildings?

**Comment by koenderks** [comment]
From the top of my ming the `key` argument is passed directly to `osmdata:: add_osm_feature()` so the description that you give in your initial comment would still apply.

In any case, I think it would be a variation of something like in the statement below. In the package everything is requested individually all the time, which is very inefficient ;)

```
.getOsmFeatures(bbox, cropped, border, features = "\"building\"=\"buildingtype\"")
```

**Comment by stalkerGH** [comment]
Thank you for valuable comment :)
