### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by stalkerGH** [koenderks/rcityviews#20]
Dear @koenderks. 

In the documentation you write about plotting separate districts of city. Could you explain content of square brackets in commands below? 

```
amsterdam <- [list_cities]("Amsterdam")[1, ]
# Create instance
center <- [new_city](
  name = "Centrum, Amsterdam",
  country = "The Netherlands",
  lat = amsterdam[1, 3],
  long = amsterdam[1, 4]
)
```

**Comment by koenderks** [comment]
The list_cities function retuns a data frame with the latitude in the third column and the longitude in the fourth column. Those are given as lat/long input to the new_city function.

**Comment by stalkerGH** [comment]
Thank you. So the parameters 1, 2, 3 and 4 are the same as columns in cities.rda?

![Screenshot_20240104_090425](https://github.com/koenderks/rcityviews/assets/25331715/0ebdc571-6dfd-4fa7-ae6d-6cf96dadc70f)

**Comment by koenderks** [comment]
Correct, they are the same. The name and country are basically the text that gets printed at the top of the image (you can also leave this blank by using the empty string “” as input) and the lat/long coordinates are printed at the bottom right and are also used to extract the OSM data.
