### ISSUE TITLE
Compact package source code

### ISSUE THREAD

**Issue by SpatLyu** [koenderks/rcityviews#22]
I want to submit some PR to reduce the package size (i.e. reduce the size of the images that come with the package). If this step offends you, please let me know.

**Comment by SpatLyu** [comment]
On my personal PC, the package didn't complete installation for a long time, and I tried to submit a PR after simplifying the package contents

``` r
version
#>                _                                
#> platform       x86_64-w64-mingw32               
#> arch           x86_64                           
#> os             mingw32                          
#> crt            ucrt                             
#> system         x86_64, mingw32                  
#> status                                          
#> major          4                                
#> minor          4.1                              
#> year           2024                             
#> month          06                               
#> day            14                               
#> svn rev        86737                            
#> language       R                                
#> version.string R version 4.4.1 (2024-06-14 ucrt)
#> nickname       Race for Your Life
```

<sup>Created on 2024-07-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by koenderks** [comment]
Hi @SpatLyu,

You are of course free to improve the package! I do not see any PR from you though, is that still relevant?

**Comment by SpatLyu** [comment]
I found an installation problem on windows, so I'm ready to reopen an issue

**Comment by koenderks** [comment]
OK go ahead, hopefully I have some time to look at it in the next day or so!
