### ISSUE TITLE
Error when  trying to install rcityviews on gnu-linux

### ISSUE THREAD

**Issue by lluisvicens** [koenderks/rcityviews#33]
**Describe the bug**
I can't install rcityviews package from github: Error on installation

**To Reproduce**
1.  When I type and execute remotes::install_github("koenderks/rcityviews", dependencies = TRUE)
2. The console throws the following error: 

Using GitHub PAT from the git credential store.
Downloading GitHub repo koenderks/rcityviews@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/koenderks/rcityviews/tarball/HEAD' failed

**Desktop (please complete the following information):**
 - OS: x86_64, linux-gnu , Linux Mint 22
 - R version 4.4.2 (2024-10-31)

Thank for your time.

**Comment by koenderks** [comment]
Did you try using the `remotes` package?

```
# install.packages("remotes") # Uncomment if 'remotes' package is not installed
remotes::install_github("koenderks/rcityviews", dependencies = TRUE)
```

**Comment by lluisvicens** [comment]
Yes, same result:

remotes::install_github("koenderks/rcityviews", dependencies = TRUE)
Using GitHub PAT from the git credential store.
Downloading GitHub repo koenderks/rcityviews@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/koenderks/rcityviews/tarball/HEAD' failed

Any hint?

**Comment by koenderks** [comment]
What if you download the .tar.gz file from https://github.com/koenderks/rcityviews/archive/refs/tags/rcityviews-v1.1.2.tar.gz and then use the install option in RStudio to install the package?

<img width="578" alt="image" src="https://github.com/user-attachments/assets/4c6b33ba-3f7c-4369-aeea-00bc2565e787">

**Comment by lluisvicens** [comment]
I worked perfectly doing this way. Thank you

**Comment by koenderks** [comment]
OK, have fun playing with it! It probably was some internet, firewall or timeout issue but since you can install it this way I will close thiss issue.

**Comment by lluisvicens** [comment]
Perfect! Your R package is great for making a nice Christmas present. ;)
