### ISSUE TITLE
Error In Installation

### ISSUE THREAD

**Issue by Heed725** [koenderks/rcityviews#4]
Hi koenderks,
Im trying to install rcityviews and im getting this error

Installing package into ‘C:/Users/hemed/OneDrive/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'rcityviews' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'rlang' 1.0.2 is already loaded, but >= 1.0.6 is required
Error: unable to load R code in package 'rcityviews'
Execution halted
ERROR: lazy loading failed for package 'rcityviews'
* removing 'C:/Users/hemed/OneDrive/Documents/R/win-library/4.1/rcityviews'
Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\00LOCK\rlang\libs\x64\rlang.dll to C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\rlang\libs\x64\rlang.dll: Permission denied
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\00LOCK\cli\libs\x64\cli.dll to C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\cli\libs\x64\cli.dll: Permission denied
3: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\00LOCK\Rcpp\libs\x64\Rcpp.dll to C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\Rcpp\libs\x64\Rcpp.dll: Permission denied
4: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\00LOCK\vctrs\libs\x64\vctrs.dll to C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\vctrs\libs\x64\vctrs.dll: Permission denied
5: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\00LOCK\terra\libs\x64\terra.dll to C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\terra\libs\x64\terra.dll: Permission denied
6: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\00LOCK\xfun\libs\x64\xfun.dll to C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\xfun\libs\x64\xfun.dll: Permission denied
7: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\00LOCK\raster\libs\x64\raster.dll to C:\Users\hemed\OneDrive\Documents\R\win-library\4.1\raster\libs\x64\raster.dll: Permission denied
8: In i.p(...) :
  installation of package ‘tidyselect’ had non-zero exit status
9: In i.p(...) :
  installation of package ‘C:/Users/hemed/AppData/Local/Temp/Rtmpi0S9bA/file24f81d4c79b5/rcityviews_1.0.3.tar.gz’ had non-zero exit status

Help

**Comment by koenderks** [comment]
Seems like you need to update your version of the `rlang` package :)

**Comment by Heed725** [comment]
It works now thanks for the help

**Comment by Heed725** [comment]
Asante sana
