### ISSUE TITLE
Choose cities or towns or areas by coordinates

### ISSUE THREAD

**Issue by mantaluke** [koenderks/rcityviews#6]
Hi Koen,

Firstly amazing package. I LOVE it. I just wondered, is it possible to pull data from a lat/long position or smaller town/village. I would like to be able to map a few smaller villages but they are not listed as cities so the package cannot find them. Any way around this?

Thanks a bunch,

**Comment by koenderks** [comment]
Hi @mantaluke,

Thanks! You currently can't choose cities by coordinates in the 'cityview()' function, it only takes names. However, in the Shiny app ('cityview_shiny()') you can use the map to zoom in on any city you like! 

Hope that helps

**Comment by mantaluke** [comment]
> Hi @mantaluke,
> 
> Thanks! You currently can't choose cities by coordinates in the 'cityview()' function, it only takes names. However, in the Shiny app ('cityview_shiny()') you can use the map to zoom in on any city you like!
> 
> Hope that helps

Great thank you,

Let me have a play with the shiny app!

**Comment by koenderks** [comment]
Closed via 2237d07e8458a31d4531fa8293a8306f2fd175ca!

**Comment by muelli** [comment]
> Check out the readme for info

I think the readme could be improved by showing how to choose a result of the `list_cities` as an input for the `cityview` function, e.g. `city <- list_cities(name = "Ams")[2,]`.

**Comment by koenderks** [comment]
> > Check out the readme for info
> 
> I think the readme could be improved by showing how to choose a result of the `list_cities` as an input for the `cityview` function, e.g. `city <- list_cities(name = "Ams")[2,]`.

OK thanks for the request, I added some clarification. See below.

> It returns a `data.frame`, so you can select a specific city by its row index (i.e., `[rowIndex, ]`).
