### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by lamontbeau** [koenderks/rcityviews#7]
Hi, 

I encountered the following installation error. Could you advise? My session information is also attached in the following.

Any help will be much appreciated! 

Warning in file(con, "r") :
  URL 'http://platform.twitter.com/widgets.js': Timeout of 60 seconds was reached
Error in file(con, "r") : 
  cannot open the connection to 'http://platform.twitter.com/widgets.js'
Error: unable to load R code in package 'rcityviews'
Execution halted
ERROR: lazy loading failed for package 'rcityviews'
* removing 'D:/Software/library/rcityviews'

############################################

> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.936  LC_CTYPE=English_Australia.936   
[3] LC_MONETARY=English_Australia.936 LC_NUMERIC=C                     
[5] LC_TIME=English_Australia.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] remotes_2.4.2

loaded via a namespace (and not attached):
[1] compiler_4.2.2 tools_4.2.2    curl_4.3.3     pacman_0.5.1

**Comment by koenderks** [comment]
I was also unable to download the package from GitHub for some time, but it seems like I am again able to install it. Maybe if you try again using:

```
# install.packages("remotes") # Uncomment if you do not have the 'remotes' package installed
remotes::install_github("koenderks/rcityviews", dependencies = TRUE)
```

If the issue is not resolved, please let me know!
